"""add task workflow tables

Revision ID: 7f02f5379407
Revises: ce0b2f4cac34
Create Date: 2026-09-01 17:30:28.705891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f02f5379407'
down_revision = 'ce0b2f4cac34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('plan_id', sa.String(length=36), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('estimated_minutes', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("priority IN ('high', 'medium', 'low')", name='ck_tasks_priority'),
    sa.CheckConstraint("status IN ('active', 'completed')", name='ck_tasks_status'),
    sa.CheckConstraint('estimated_minutes >= 0', name='ck_tasks_estimated_minutes'),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_plan_id'), ['plan_id'], unique=False)

    op.create_table('task_tags',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('value', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'value', name='uq_task_tag_value')
    )
    with op.batch_alter_table('task_tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_tags_task_id'), ['task_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_tags_task_id'))

    op.drop_table('task_tags')
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_plan_id'))

    op.drop_table('tasks')
    # ### end Alembic commands ###
