"""add reflections and next plan link

Revision ID: b84587642a1b
Revises: fb630bb3ebd6
Create Date: 2026-09-01 20:17:57.383942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b84587642a1b'
down_revision = 'fb630bb3ebd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reflections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('plan_id', sa.String(length=36), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('improvement', sa.Text(), nullable=False),
    sa.Column('next_plan_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('period_end >= period_start', name='ck_reflection_period'),
    sa.ForeignKeyConstraint(['next_plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reflections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reflections_plan_id'), ['plan_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reflections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reflections_plan_id'))

    op.drop_table('reflections')
    # ### end Alembic commands ###
