"""create plan history tables

Revision ID: ce0b2f4cac34
Revises: 
Create Date: 2026-09-01 17:21:02.352060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce0b2f4cac34'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('success_criterion', sa.Text(), nullable=False),
    sa.Column('estimated_minutes', sa.Integer(), nullable=False),
    sa.Column('carried_improvement', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("priority IN ('high', 'medium', 'low')", name='ck_plans_priority'),
    sa.CheckConstraint('end_date >= start_date', name='ck_plans_date_order'),
    sa.CheckConstraint('estimated_minutes >= 0', name='ck_plans_estimated_minutes'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plan_revisions',
    sa.Column('revision_id', sa.String(length=36), nullable=False),
    sa.Column('plan_id', sa.String(length=36), nullable=False),
    sa.Column('revision_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('success_criterion', sa.Text(), nullable=False),
    sa.Column('estimated_minutes', sa.Integer(), nullable=False),
    sa.Column('carried_improvement', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('replaced_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('estimated_minutes >= 0', name='ck_plan_revision_estimated_minutes'),
    sa.CheckConstraint('revision_number >= 1', name='ck_plan_revision_number'),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('revision_id'),
    sa.UniqueConstraint('plan_id', 'revision_number', name='uq_plan_revision_number')
    )
    with op.batch_alter_table('plan_revisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plan_revisions_plan_id'), ['plan_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plan_revisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plan_revisions_plan_id'))

    op.drop_table('plan_revisions')
    op.drop_table('plans')
    # ### end Alembic commands ###
