"""add execution logs and completion events

Revision ID: fb630bb3ebd6
Revises: 7f02f5379407
Create Date: 2026-09-01 20:03:39.822172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb630bb3ebd6'
down_revision = '7f02f5379407'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('completion_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('idempotency_key', sa.String(length=100), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'idempotency_key', name='uq_completion_task_key')
    )
    with op.batch_alter_table('completion_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_completion_events_task_id'), ['task_id'], unique=False)

    op.create_table('execution_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actual_minutes', sa.Integer(), nullable=False),
    sa.Column('blocker_reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('actual_minutes BETWEEN 0 AND 1000000', name='ck_execution_minutes'),
    sa.CheckConstraint('ended_at > started_at', name='ck_execution_time_order'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('execution_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_execution_logs_task_id'), ['task_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('execution_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_execution_logs_task_id'))

    op.drop_table('execution_logs')
    with op.batch_alter_table('completion_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_completion_events_task_id'))

    op.drop_table('completion_events')
    # ### end Alembic commands ###
